packages:
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
overrides:
  '@expo/cli': '57.0.9'
  '@expo/config-plugins': '57.0.5'
  '@expo/config': '57.0.5'
  '@expo/fingerprint': '0.20.5'
  '@expo/image-utils': '0.11.3'
  '@expo/metro-config': '57.0.6'
  '@expo/prebuild-config': '57.0.8'
  '@expo/require-utils': '57.0.3'
  '@expo/router-server': '57.0.3'
  babel-preset-expo: '57.0.3'
  expo-asset: '57.0.6'
  expo-modules-autolinking: '57.0.8'
  expo-modules-core: '57.0.6'
  expo-modules-jsi: '57.0.3'
