import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { GpsProvider, UserRole } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { AuthenticatedUser } from '../auth/auth.types';
import { encryptCredentials } from '../../common/credentials-encryption';
import { UpsertGpsProviderConfigDto } from './dto/upsert-gps-provider-config.dto';

function assertOwner(actor: AuthenticatedUser): void {
  if (actor.role !== UserRole.OWNER) {
    throw new ForbiddenException('Only OWNER may manage the GPS provider connection');
  }
}

/**
 * Stage 1b - what GET/PUT/PATCH return. Deliberately never
 * credentialsEncrypted or any decrypted value, in any form: hasCredentials
 * is the one bit a caller needs (a token is on file) without ever seeing or
 * being able to re-derive it.
 */
export interface GpsProviderConfigView {
  baseUrl: string;
  isActive: boolean;
  lastPolledAt: string | null;
  lastSuccessAt: string | null;
  lastErrorMessage: string | null;
  hasCredentials: boolean;
}

type ConfigRow = {
  baseUrl: string;
  isActive: boolean;
  lastPolledAt: Date | null;
  lastSuccessAt: Date | null;
  lastErrorMessage: string | null;
  credentialsEncrypted: Uint8Array;
};

@Injectable()
export class GpsProviderConfigService {
  constructor(private readonly prisma: PrismaService) {}

  /** One provider today (TRACCAR), but keyed the same way GpsProviderConfig's
   *  own [tenantId, provider] unique constraint is, so a second provider is
   *  additive later rather than a shape change. */
  private uniqueWhere(actor: AuthenticatedUser) {
    return { tenantId_provider: { tenantId: actor.tenantId, provider: GpsProvider.TRACCAR } };
  }

  /** Null (not a 404) when this tenant hasn't configured a connection yet -
   *  an ordinary, expected state for a fresh tenant, not an error. */
  async get(actor: AuthenticatedUser): Promise<GpsProviderConfigView | null> {
    assertOwner(actor);
    const config = await this.prisma.client.gpsProviderConfig.findUnique({
      where: this.uniqueWhere(actor),
    });
    return config ? this.toView(config) : null;
  }

  /**
   * Upserts THIS tenant's TRACCAR config. lastErrorMessage resets to null
   * on every credential update - a fresh credential deserves a fresh chance
   * before being judged broken by whatever the old one last failed with.
   * Also sets isActive: true unconditionally: PUT is the only way to
   * recover a deactivated config back into polling (there is no separate
   * "activate" endpoint, only PATCH .../deactivate), so submitting a
   * (possibly corrected) credential is what reactivates it.
   */
  async upsert(
    dto: UpsertGpsProviderConfigDto,
    actor: AuthenticatedUser,
  ): Promise<GpsProviderConfigView> {
    assertOwner(actor);
    // Prisma's generated Bytes input type wants a plain ArrayBuffer-backed
    // Uint8Array, not Node's Buffer (typed as ArrayBufferLike, which also
    // admits SharedArrayBuffer) - copied here purely to satisfy that, same
    // bytes either way.
    const credentialsEncrypted = new Uint8Array(
      encryptCredentials(JSON.stringify({ token: dto.token })),
    );

    const config = await this.prisma.client.gpsProviderConfig.upsert({
      where: this.uniqueWhere(actor),
      create: {
        tenantId: actor.tenantId,
        provider: GpsProvider.TRACCAR,
        baseUrl: dto.baseUrl,
        credentialsEncrypted,
        isActive: true,
      },
      update: {
        baseUrl: dto.baseUrl,
        credentialsEncrypted,
        isActive: true,
        lastErrorMessage: null,
      },
    });
    return this.toView(config);
  }

  async deactivate(actor: AuthenticatedUser): Promise<GpsProviderConfigView> {
    assertOwner(actor);
    const existing = await this.prisma.client.gpsProviderConfig.findUnique({
      where: this.uniqueWhere(actor),
    });
    if (!existing) {
      throw new NotFoundException('No GPS provider connection is configured for this tenant');
    }

    const config = await this.prisma.client.gpsProviderConfig.update({
      where: { id: existing.id },
      data: { isActive: false },
    });
    return this.toView(config);
  }

  private toView(config: ConfigRow): GpsProviderConfigView {
    return {
      baseUrl: config.baseUrl,
      isActive: config.isActive,
      lastPolledAt: config.lastPolledAt?.toISOString() ?? null,
      lastSuccessAt: config.lastSuccessAt?.toISOString() ?? null,
      lastErrorMessage: config.lastErrorMessage,
      hasCredentials: config.credentialsEncrypted.length > 0,
    };
  }
}
